version: '1'
services:

  conversion-postgres:
    image: "postgres:9.6-alpine"
    container_name: conversion-postgres
    volumes:
      - conversion-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=conversion
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  conversion:
    build: ./conversion-app
    container_name: conversion
    volumes:
      - ./conversion-app/src:/app/target_dir
    environment:
      - DB_SERVER=conversion-postgres
      - POSTGRES_DB=conversion
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 8080:8080
    links:
      - conversion-postgres

volumes:
  conversion-data: